# Generated by Django 4.2.5 on 2024-10-30 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoplayer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='image',
            field=models.ImageField(null=True, upload_to='image/'),
        ),
    ]
