# Generated by Django 4.2.5 on 2024-10-31 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoplayer', '0002_alter_video_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='image',
            field=models.ImageField(null=True, upload_to='video_preview/'),
        ),
    ]
