# Generated by Django 4.2.5 on 2024-11-10 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoplayer', '0003_alter_video_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='file',
        ),
        migrations.AddField(
            model_name='video',
            name='file_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
