# Generated by Django 4.2.5 on 2025-05-09 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_lesson_access_rights'),
        ('videoplayer', '0004_remove_video_file_video_file_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='access_rights',
            field=models.ManyToManyField(blank=True, to='user.accessright'),
        ),
    ]
