# Generated by Django 4.2.5 on 2024-09-17 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videoplayer', '0001_initial'),
        ('serverpart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pack_video', to='videoplayer.video'),
        ),
    ]
