# Generated by Django 4.2.5 on 2024-10-15 22:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('serverpart', '0002_pack_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolvedPacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.PositiveIntegerField(default=0, max_length=100)),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serverpart.pack')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SolvedPacks',
                'verbose_name_plural': 'SolvedPacks',
            },
        ),
    ]
