# Generated by Django 4.2.5 on 2024-10-29 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videoplayer', '0001_initial'),
        ('serverpart', '0004_alter_solvedpacks_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pack',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pack_video', to='videoplayer.video'),
        ),
    ]
