# Generated by Django 4.2.5 on 2024-04-16 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverpart', '0004_alter_task_answer_alter_task_task_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='solution_image',
            field=models.ImageField(blank=True, upload_to='solution_images/'),
        ),
    ]
