# Generated by Django 4.2.5 on 2024-04-16 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverpart', '0005_alter_task_solution_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='solution_image',
            field=models.ImageField(blank=True, upload_to='media/solution_images/'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_image',
            field=models.ImageField(upload_to='media/task_images/'),
        ),
    ]
