# Generated by Django 4.2.5 on 2024-04-16 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverpart', '0006_alter_task_solution_image_alter_task_task_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='solution_image',
            field=models.ImageField(blank=True, upload_to='solution_images/'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_image',
            field=models.ImageField(upload_to='task_images/'),
        ),
    ]
