# Generated by Django 4.2.5 on 2025-05-09 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_lesson_access_rights'),
        ('serverpart', '0006_remove_pack_text_field_readingimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='access_rights',
            field=models.ManyToManyField(blank=True, to='user.accessright'),
        ),
    ]
