# Generated by Django 4.2.5 on 2024-05-06 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverpart', '0007_alter_task_solution_image_alter_task_task_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='test_number',
            field=models.IntegerField(editable=False, unique=True),
        ),
    ]
