# Generated by Django 4.2.5 on 2024-08-28 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serverpart', '0008_alter_test_test_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_field', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='task',
            name='section',
        ),
        migrations.RemoveField(
            model_name='task',
            name='solution_image',
        ),
        migrations.RemoveField(
            model_name='task',
            name='subsection',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_number',
        ),
        migrations.RemoveField(
            model_name='task',
            name='theme',
        ),
        migrations.AddField(
            model_name='subsection',
            name='section',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='serverpart.section'),
        ),
        migrations.DeleteModel(
            name='Theme',
        ),
        migrations.AddField(
            model_name='pack',
            name='subsection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serverpart.subsection'),
        ),
        migrations.AddField(
            model_name='task',
            name='pack',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='serverpart.pack'),
            preserve_default=False,
        ),
    ]
