# Generated by Django 4.2.5 on 2024-08-28 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serverpart', '0009_pack_remove_task_section_remove_task_solution_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsection',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serverpart.section'),
        ),
    ]
