# Generated by Django 4.2.5 on 2024-10-16 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_subscription_subscriptionlist_delete_subscribe'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='subscription',
            name='access_rights',
            field=models.ManyToManyField(to='user.accessright'),
        ),
    ]
