# Generated by Django 4.2.5 on 2024-10-16 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_accessright_subscription_access_rights'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='access_rights',
            field=models.ManyToManyField(blank=True, to='user.accessright'),
        ),
    ]
