# Generated by Django 4.2.5 on 2025-01-29 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_lesson_userlessonprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='upload_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
