# Generated by Django 4.2.5 on 2025-05-09 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_lesson_upload_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='access_rights',
            field=models.ManyToManyField(blank=True, to='user.accessright'),
        ),
    ]
